name: stream_chatter
description: Chat App implemented using Clean Architecture.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^7.1.0
  stream_chat_flutter: ^3.0.0
  uuid: ^3.0.5

  firebase_core: ^1.7.0
  google_sign_in: ^5.1.1
  firebase_auth: ^3.1.2
  firebase_storage: ^10.0.4
  shared_preferences: ^2.0.8
  http: any
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
     - assets/